# https://www.home-assistant.io/integrations/default_config/
default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# https://www.home-assistant.io/integrations/logger/
logger:
  default: warning
  logs:
    custom_components.label_state: debug

debugpy:
  start: true
  wait: false
  port: 5678
